# Generated by Django 3.2.1 on 2021-07-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backflix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, unique=True)),
                ('cor', models.CharField(max_length=7)),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='titulo',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
